name: Check Formatting (comment /format to auto-fix)

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    types: [checks_requested]
jobs:
  check-formatting:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/format-setup
      - run: ./extras/formatting.sh --check-only
